//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_com.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public int adminsId { get; set; }
        public string adminsName { get; set; }
        public string adminsEmail { get; set; }
        public string adminsPass { get; set; }
        public Nullable<int> role_AdminId { get; set; }
    
        public virtual role_Admin role_Admin { get; set; }
    }
}
