//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_com.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class author_Warning
    {
        public int author_WarningId { get; set; }
        public string author_WarningReason { get; set; }
        public Nullable<int> author_WarningWorkId { get; set; }
        public Nullable<System.DateTime> author_WarningDate { get; set; }
        public Nullable<int> authorId { get; set; }
    
        public virtual work work { get; set; }
        public virtual user user { get; set; }
    }
}
