//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_com.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class author_Follow
    {
        public int author_FollowId { get; set; }
        public Nullable<int> followerId { get; set; }
        public Nullable<int> authorId { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
