//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_com.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class badge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public badge()
        {
            this.user_Badge = new HashSet<user_Badge>();
        }
    
        public int badgeId { get; set; }
        public string badgeName { get; set; }
        public string badgeDescription { get; set; }
        public Nullable<bool> isForAuthor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_Badge> user_Badge { get; set; }
    }
}
