//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_com.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment_Heart
    {
        public int comment_HeartId { get; set; }
        public int usersId { get; set; }
        public int work_CommentId { get; set; }
    
        public virtual user user { get; set; }
        public virtual work_Comment work_Comment { get; set; }
    }
}
