//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_com.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_MessageBlock
    {
        public int user_MessageBlockId { get; set; }
        public Nullable<System.DateTime> user_MessageBlockSentAt { get; set; }
        public Nullable<int> userId_Block { get; set; }
        public Nullable<int> userId_GetBlocked { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
