//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_com.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_Conversation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user_Conversation()
        {
            this.user_ConversationParticipant = new HashSet<user_ConversationParticipant>();
            this.user_Message = new HashSet<user_Message>();
        }
    
        public int user_ConversationId { get; set; }
        public int user_ConversationStatus { get; set; }
        public Nullable<System.DateTime> user_ConversationDate { get; set; }
        public Nullable<System.DateTime> user_ConversationLast { get; set; }
        public Nullable<int> userId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_ConversationParticipant> user_ConversationParticipant { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_Message> user_Message { get; set; }
    }
}
