//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_com.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_Notification
    {
        public int user_NotificationId { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> actorId { get; set; }
        public Nullable<int> workId { get; set; }
        public Nullable<int> commentId { get; set; }
        public string user_NotificationType { get; set; }
        public Nullable<bool> isRead { get; set; }
        public Nullable<System.DateTime> user_NotificationCreated { get; set; }
    
        public virtual user user { get; set; }
        public virtual work_Comment work_Comment { get; set; }
        public virtual user user1 { get; set; }
        public virtual work work { get; set; }
    }
}
