//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_com.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_Warning
    {
        public int user_WarningId { get; set; }
        public string user_WarningType { get; set; }
        public string user_WarningReason { get; set; }
        public Nullable<int> user_WarningLevel { get; set; }
        public Nullable<System.DateTime> user_WarningDate { get; set; }
        public Nullable<int> userId { get; set; }
    
        public virtual user user { get; set; }
    }
}
