//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_com.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_Message
    {
        public int user_MessageId { get; set; }
        public string user_MessageContext { get; set; }
        public Nullable<System.DateTime> user_MessageSentAt { get; set; }
        public Nullable<bool> user_MessageIsDelete { get; set; }
        public Nullable<int> user_ConversationId { get; set; }
        public Nullable<int> userId { get; set; }
    
        public virtual user_Conversation user_Conversation { get; set; }
        public virtual user user { get; set; }
    }
}
