//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_com.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_Badge
    {
        public int userId { get; set; }
        public int badgeId { get; set; }
        public Nullable<System.DateTime> user_BadgeObtained { get; set; }
    
        public virtual badge badge { get; set; }
        public virtual user user { get; set; }
    }
}
