//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_com.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class web_comEntities : DbContext
    {
        public web_comEntities()
            : base("name=web_comEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<author_Follow> author_Follow { get; set; }
        public virtual DbSet<author_Warning> author_Warning { get; set; }
        public virtual DbSet<badge> badges { get; set; }
        public virtual DbSet<comment_Heart> comment_Heart { get; set; }
        public virtual DbSet<genre> genres { get; set; }
        public virtual DbSet<role_Admin> role_Admin { get; set; }
        public virtual DbSet<tag> tags { get; set; }
        public virtual DbSet<user_Badge> user_Badge { get; set; }
        public virtual DbSet<user_History> user_History { get; set; }
        public virtual DbSet<user_Warning> user_Warning { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<work> works { get; set; }
        public virtual DbSet<work_Arc> work_Arc { get; set; }
        public virtual DbSet<work_Chapter> work_Chapter { get; set; }
        public virtual DbSet<work_ChapterImage> work_ChapterImage { get; set; }
        public virtual DbSet<work_Comment> work_Comment { get; set; }
        public virtual DbSet<work_Favorite> work_Favorite { get; set; }
        public virtual DbSet<work_Heart> work_Heart { get; set; }
        public virtual DbSet<work_Status> work_Status { get; set; }
        public virtual DbSet<work_Tag> work_Tag { get; set; }
        public virtual DbSet<work_View> work_View { get; set; }
    }
}
