//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_com.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class work_ChapterImage
    {
        public int work_ChapterImageId { get; set; }
        public string work_ChapterImageName { get; set; }
        public int work_ChapterImageOrder { get; set; }
        public int work_ChapterId { get; set; }
    
        public virtual work_Chapter work_Chapter { get; set; }
    }
}
