//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_com.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class work_Comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public work_Comment()
        {
            this.comment_Heart = new HashSet<comment_Heart>();
        }
    
        public int work_CommentId { get; set; }
        public string work_CommentContent { get; set; }
        public Nullable<System.DateTime> work_CommentCreated { get; set; }
        public Nullable<bool> work_CommentIsApproved { get; set; }
        public Nullable<bool> work_CommentIsDeleted { get; set; }
        public Nullable<int> workId { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> arcId { get; set; }
        public Nullable<int> chapterId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment_Heart> comment_Heart { get; set; }
        public virtual user user { get; set; }
        public virtual work work { get; set; }
        public virtual work_Arc work_Arc { get; set; }
        public virtual work_Chapter work_Chapter { get; set; }
    }
}
