//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_com.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class work
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public work()
        {
            this.author_Warning = new HashSet<author_Warning>();
            this.user_History = new HashSet<user_History>();
            this.work_Arc = new HashSet<work_Arc>();
            this.work_Comment = new HashSet<work_Comment>();
            this.work_Favorite = new HashSet<work_Favorite>();
            this.work_Heart = new HashSet<work_Heart>();
            this.work_Tag = new HashSet<work_Tag>();
            this.work_View = new HashSet<work_View>();
        }
    
        public int workId { get; set; }
        public string workName { get; set; }
        public Nullable<System.DateTime> workCreated { get; set; }
        public string workImage { get; set; }
        public Nullable<int> genreId { get; set; }
        public Nullable<int> authorId { get; set; }
        public Nullable<int> work_StatusId { get; set; }
        public string workOverview { get; set; }
        public Nullable<bool> isDisabled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<author_Warning> author_Warning { get; set; }
        public virtual genre genre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_History> user_History { get; set; }
        public virtual user user { get; set; }
        public virtual work_Status work_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<work_Arc> work_Arc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<work_Comment> work_Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<work_Favorite> work_Favorite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<work_Heart> work_Heart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<work_Tag> work_Tag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<work_View> work_View { get; set; }
    }
}
